conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path ('new/<int:item_pk>/', views.new_conversation, name='new'), 
    path ('', views.inbox, name='inbox'), 
    path ('<int:pk>/', views.detail, name='detail'),

]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm


app_name = 'core'

urlpatterns = [
    path ('', views.index, name = 'index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name ='logout'),
    
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path ('', views.index, name = 'index'),
]

django_online_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static

#izbrisat na produkciji ovo gore 


from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include ('core.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('items', include ('item.urls')),
    path('dashboard', include('dashboard.urls')),
    
    


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path


from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'), 
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'), 

     

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))




class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2' )

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item

from . forms import SignupForm

# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render (request, 'core/index.html',{
        'categories': categories,
        'items': items, 
        })

def contact(request):
    return render (request, 'core/contact.html')


def signup (request):
    if request.method =='POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()


    return render (request, 'core/signup.html',{
        'form': form
    })

core/templates/core/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}  {% endblock %} Web shop</title>
</head>


<body>

  <!-- Navbar -->
<nav class="bg-gray-800 p-5 flex justify-between items-center">

  <!-- Online Shop Section -->
  
  <div class="text-white">
    <a href="/">
        <h1 class="text-2xl font-bold text-teal-500 hover:text-teal-700">Kupovina online</h1>
    </a>
</div>

  <!-- Mobile Menu Button -->
  <button id="menu-toggle" class="lg:hidden text-white hover:text-green-500 focus:outline-none">
      <svg class="h-6 w-6" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
          <path d="M4 6h16M4 12h16M4 18h16"></path>
      </svg>
  </button>

  <!-- Right Side Buttons -->
  <div class="hidden lg:flex space-x-4">

     <!-- New Item Button -->
     <a href="{% url 'item:new' %}">
      <button class="text-white hover:text-green-500">Novi artikal</button>
     </a>
  
     <!-- Browse Inbox Button -->
     <a href="{% url 'item:items' %}">
      <button class="text-white hover:text-green-500">Pretraga</button>
     </a>
   

    

    {% if request.user.is_authenticated %}

     <!-- Browse Inbox Button -->
     <a href="{% url 'conversation:inbox' %}">
      <button class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Inbox</button>
     </a>

     <!-- Dashboard Button -->
     <a href="{% url 'dashboard:index' %}">
      <button class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Pregled</button>
     </a>
     <!-- Log Out Button -->
     <a href="{% url 'core:logout' %}">
      <button class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Odjava</button>
     </a>
     
     {% else %}
     <a href="{% url 'core:signup' %}">
      <button class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Registracija</button>
     </a>

     <!-- Log IN Button -->
     <a href="{% url 'core:login' %}">
      <button class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Prijava</button>
     </a>

     
     

           
    {% endif %}


  </div>
</nav>

<!-- Mobile Menu (Hidden on Desktop) -->
<div id="mobile-menu" class="lg:hidden absolute top-16 right-0 mt-2 bg-gray-900 w-48 rounded-lg shadow-md hidden">
  <button id="menu-toggle" class="text-white hover:text-green-500 focus:outline-none right-4 top-4 absolute">
      <svg class="h-6 w-6" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
          
      </svg>
  </button>

  <!-- Menu Text -->
  

  <!-- Mobile Menu Links -->
  <ul class="block space-y-2 p-4">
    <li><a href="{% url 'item:new' %}" class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Novi artikal</a></li>
      <li><a href="{% url 'item:items' %}" class="text-lg font-semibold text-gray-800 bg-teal-500 hover:bg-teal-700 text-white rounded-lg px-6 py-2">Pretraga</a></li>
    {% if request.user.is_authenticated %}
      
      <li><a href="{% url 'conversation:inbox' %}" class="text-white hover:text-green-500">Inbox</a></li>
      <li><a href="{% url 'dashboard:index' %}" class="text-white hover:text-green-500">Pregled</a></li>
      <li><a href="{% url 'core:logout' %}" class="text-white hover:text-green-500">Odjava</a></li>
      {% else %}

      <li><a href="{% url 'core:login' %}" class="text-white hover:text-green-500">Prijava</a></li>
      <li><a href="{% url 'core:signup' %}" class="text-white hover:text-green-500">Registracija</a></li>
      {% endif %}



  </ul>
  <script>
    // Function to toggle the mobile menu
    function toggleMobileMenu() {
        var mobileMenu = document.getElementById("mobile-menu");
        if (mobileMenu.style.display === "block") {
            mobileMenu.style.display = "none";
        } else {
            mobileMenu.style.display = "block";
        }
    }

    // Add a click event listener to the menu-toggle button
    document.getElementById("menu-toggle").addEventListener("click", toggleMobileMenu);
</script>
</div>



    

    <div class="px-6 py-6">

        {% block content %}
        {% endblock %}
        
    </div>
    
    <footer class="py-6 px-6 sm:py-8 sm:px-12 flex flex-col sm:flex-row justify-between items-center bg-gray-800">
        <div class="w-full sm:w-1/2 pr-6 sm:pr-10">
            <h3 class="mb-4 text-2xl text-teal-500 font-semibold">About Us</h3>
            <p class="text-lg text-gray-400">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
        </div>
    
        <div class="w-full sm:w-1/4">
            <h3 class="mb-4 text-2xl text-teal-500 font-semibold">Quick Links</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-gray-300 hover:text-teal-500">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-gray-300 hover:text-teal-500">Contact</a></li>
                <li><a href="#" class="text-lg text-gray-300 hover:text-teal-500">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-gray-300 hover:text-teal-500">Terms of Use</a></li>
            </ul>
        </div>
    </footer>
    
    
</body>



</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}



{% block content %}

<h1>Kontakt stranica</h1>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Novi artikli</h2>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {% for item in items %}
        <a href="{% url 'item:detail' item.id %}" class="bg-white rounded-xl hover:shadow-md">
            <img src="{{ item.image.url }}" class="rounded-t-xl w-full h-48 object-cover" alt="{{ item.name }}">
            <div class="px-6 py-4">
                <h2 class="text-xl font-semibold">{{ item.name }}</h2>
                <p class="text-gray-500">Price: {{ item.price }}</p>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Kategorije</h2>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {% for category in categories %}
        <a href="" class="bg-white rounded-xl hover:shadow-md">
            <div class="px-6 py-4">
                <h2 class="text-xl font-semibold">{{ category.name }}</h2>
                <p class="text-gray-500">{{ category.items.count }} items</p>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Prijava {% endblock %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

       

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors}}
            {% endfor %}

            {{ form.non_field_errors }}

        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Prijavi se</button>

    </form>
</div>

{% endblock %}

core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %} Odjava {% endblock %}



{% block content %}

<h1>You are succesfully logged out</h1>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Registracija {% endblock %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Registracija</h1>

    <form method="post" action=".">
        {% csrf_token %}

        

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Šifra</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Ponovi šifru</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors}}
            {% endfor %}

            {{ form.non_field_errors }}

        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Registruj se</button>

    </form>
</div>

{% endblock %}